# permissions for end users to edit githubreleasesmonitors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: archops-cve-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubreleasesmonitor-editor-role
rules:
- apiGroups:
  - cve-producer.archops.com
  resources:
  - githubreleasesmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cve-producer.archops.com
  resources:
  - githubreleasesmonitors/status
  verbs:
  - get
