apiVersion: cve-producer.archops.com/v1
kind: GitHubReleasesMonitor
metadata:
  labels:
    app: githubreleases-monitor
    app.kubernetes.io/name: archops-cve-operator
    app.kubernetes.io/managed-by: kustomize
  name: githubreleases-monitor
spec:
  url: https://github.com/CVEProject/cvelistV5/releases
  monitorFrom: "2024-07-24"
  helmReleaseName: cve-operator
  githubReleaseJobConfig:
    image: niteshmore22/webapp-cve-processor:latest
    imagePullPolicy: Always
    backoffLimit: 3
    ttlSecondsAfterFinished: 100